### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by eblin**
Hey @nixgates 

Review the commits and let me know if you have any questions or if you want me to squash the commits.

After further testing the 2e3d553 commit seems to fix all the default settings not loading properly without the need to change any other code 👍

### CODE REVIEW

**Comment by nixgates** [comment]
My concern for this is that the settings cache was put in to reduce the log spam from Kodi about the settings being in an old format and the settings fix removes that caches purpose.

What I'd probably suggest is to replace this change with a check to confirm the settings cache value is not an empty string as what I believe is returned on getSetting failing to get the correct value.

Could I ask you to test this on a ATV device?

**Comment by nixgates** [comment]
Apologies, I fat finger closed by accident. I've re-opened the PR

**Comment by nixgates** [comment]
Holy shit, I see where I fucked up and what's failing now.

This is all perfect thank you.

**Comment by eblin** [comment]
@nixgates But the settings cache is still there, I didn’t remove it at all. 

Also I checked the logs and I didn’t see anything about Kodi complaining about old format, perhaps that only happens on Android? And the settings cache works properly for example after you got to menu and close it. 

But ya I can test what you suggested.

**Comment by eblin** [comment]
Also take a look at https://github.com/nixgates/plugin.video.seren/commit/f7887545caf119c47e7e0fefc90675350336987d

the only change on getSetting I did was I return value early if not in console mode just like you do on setSetting. 

Without this, it would call Kodi getSetting and continue on to the XML read file code which is not necessary when not in console mode. This does trigger log errors as it can’t read the settings file for some reason.

**Comment by nixgates** [comment]
Yea haha as I replied I just realised this whole issue is because I failed to add the early return for the function which is why I was so confused as to why that was there as a change. 

Either way, I see the issue you found and I'm 100% for this PR. Once I'm back at my main PC I'll flick through a hot fix to the repo with this merged.

**Comment by eblin** [comment]
No problem, I’ve had my share of those as well 😂 glad I could help 👍

**Comment by eblin** [comment]
> I'll have to get you to edit this PR as this will break meta updates for items and lines 100 and 101 the activities file already cover commit `a423845`

Line 100, 101 are there but line 40 will execute first causing the oauth error since `trakt.auth` is empty and you're going to get the dialog popup even if you have not setup trakt

Feel free to just get the needed changes too, you don't have to merge the PR if that works :)

**Comment by nixgates** [comment]
I think you've actually caught a new bug that hasn't been identified yet. As it looks like lines 66-97 won't run unless the user has trakt authorised which is incorrect. I'll fix that this update to.

But yea I'll close this off

**Comment by nixgates** [comment]
Sorry, I'm hung over and that last reply looks so passive aggressive lol.

I've manually added your changes 😅

**Pull request closed without merging**
