### PR TITLE
Update English to Danish strings.po

### PR DESCRIPTION
**Pull request by mLgz0rn**
Work in progress, but updated some of the translation

### CODE REVIEW

**Comment by nixgates** [comment]
@mLgz0rn I believe I've got this in ok, can you confirm for me?

**Comment by mLgz0rn** [comment]
Looks alright! :)
I made a small booboo on line 211-213
Should be

```
msgstr ""
"Vær opmærksom på, at dette vil rydde følgende permanent:\n"
"Cached Data, Indstillinger, Installerede Udbydere\n"
```

**Comment by nixgates** [comment]
@mLgz0rn ok I'll fix this up :)

**Comment by nixgates** [comment]
@mLgz0rn all done for next update! :)

**Pull request closed without merging**
