### PR TITLE
Add search history

### PR DESCRIPTION
**Pull request by acv1234**
Please add a search history function so entering the title is not needed for something that has already been searched for.

sorry not sure how this happened.

### CODE REVIEW

**Comment by drinfernoo** [comment]
That's been implemented already, for a long time.

**Comment by SasukeShiro** [comment]
You have to enable through settings

**Comment by drinfernoo** [comment]
@nixgates, search history *should* probably be enabled by default.

**Comment by nixgates** [comment]
Sorry search history has been implemented for some time now but thank you for helping out :)

**Pull request closed without merging**
