### PR TITLE
small bug fixes

### PR DESCRIPTION
**Pull request by jorritsmit**
I noticed that during your last update the busydialog was properly closed when no links were found, however it is not closed when the stream url cannot be resolved, this should fix that. The other thing i noticed is that one notification is held silent when i don't think it is supposed to be.

### CODE REVIEW

**Comment by nixgates** [comment]
If you wouldn't mind clearing the notification changes in the getSources module I'd be happy to merge your commits :)

**Comment by jorritsmit** [comment]
Of course, but can I ask why you choose to make this message silent only when the other ones are not silent? In other words, all the other conditions are: if not silent then notify , This one is: if silent then notify

**Comment by nixgates** [comment]
If you wouldnt mind raising a git issue to track this rather than full this pull request.

In regards to the notification, that's there in case there no sources for the next episode at all. The get sources module is only silent during pre-emptive scraping. If Seren can't find any sources in the pre-emptive scraping the playlist is cleared and Kodi stops playing after the current item finishes.

Without this the user might assume a bug is causing Seren to clear and stop playing after an episode. This small notification at least allows a user to be notified that an issue has occured.

**Comment by nixgates** [comment]
If you wouldnt mind raising a git issue to track this rather than full this pull request.

In regards to the notification, that's there in case there no sources for the next episode at all. The get sources module is only silent during pre-emptive scraping. If Seren can't find any sources in the pre-emptive scraping the playlist is cleared and Kodi stops playing after the current item finishes.

Without this the user may assume a bug is causing Seren to clear and stop playing after an episode. This small notification at least allows a user to be notified of what's happening and why.

**Comment by nixgates** [comment]
@jorritsmit

Hey I do apologize for this, someone outside of GitHub spent a lot of time working on this exact issue and other bugs, I've incorporated their changes into the master but it obviously conflicts with some of yours. 

If you see anything that can be added or something that was missed please let me know!

I'm sorry to close this off.

**Pull request closed without merging**
