### PR TITLE
inb4after patch: Fix pre-emptive termination, Add Next Up Reverse Sort option, Add Separate Minimum Sources Sliders

### PR DESCRIPTION
**Pull request by inb4after**
Direct download link for testers:

https://github.com/inb4after/plugin.video.seren/archive/inb4after-patch.zip

Fixed pre-emptive termination #303:

On first scrape of movies (in particular but not limited to), pre-emptive termination does not terminate effectively for the chosen resolution, seeming random. The patch will allow only the chosen resolution to affect pre-emptive termination, rather than all of them (which were also reversed so SD was prioritized).

Add Next Up Reverse Sort option #358:

This feature now allows user to reverse the up next sort order, particularly useful on left-side menu based skins.

Add Separate Minimum Sources Sliders #274:

This feature now allows user to select different values for Movies vs TV shows to pre-emptively terminate on.

I'm open to feedback and user testing of the fix and additions. Thanks in advance.

-inb4after

PS: Edits also welcome as I'm a coding newb 😅. Also, new to github, sorry for the multiple duplicate PR, the old PR can be deleted and this PR (inb4after-patch) is now the main.

### CODE REVIEW

**Comment by inb4after** [comment]
Direct download link for testers:
https://github.com/inb4after/plugin.video.seren/archive/inb4after-patch.zip

**Comment by streamindemons** [comment]
tested and compared to Normal seren without the patch, sure enough the issues described happened and were fixed with this patch. Great job!

**Comment by inb4after** [comment]
@nixgates I would still like to see separate minimum sources sliders and reverse sorting of Next Up, would it require more user testing/feedback?

**Comment by inb4after** [comment]
Updated for 2.0.12 (barely... thanks to github desktop for messing up my branch)

**Comment by inb4after** [comment]
Updated for 2.0.12 (barely... thanks to github desktop for messing up my branch)

**Comment by inb4after** [comment]
Closed as requested

**Pull request closed without merging**
